apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetis-deploy
  labels: 
   app: flasgger
   tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: flasgger
      tier: frontend
  template:
    metadata:
      labels:
        app: flasgger
        tier: frontend
    spec:
      containers:
      - name: diabetis-container
        image: muralidhar123/diabetis:v1
        ports: 
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: diabetis-service
  labels:
    app: flasgger
    tier: frontend
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata: 
  name: frontend-service
  labels: 
    app: flasgger
    tier: frontend
spec:
  type: NodePort 
  selector: 
    app: flasgger
    tier: frontend
  ports: 
  - port: 5000
